name: Download

on:
    schedule:
        -   cron: 34 0 * * *
    workflow_dispatch:

permissions: write-all

jobs:
    card_number:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "main", "1.x" ]
        with:
            project: Card Number ${{ matrix.version }}
            paths: source/card-number/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/TheDragonCode/card-number/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=card-number \
                    --ver=${{ matrix.version }}
